// import Navbar from "@/components/Navbar";

import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { AuthProvider } from "./contexts/AuthContext";
import Navbar from "./components/Navbar";
import Header from "./components/Header";

const inter = Lato({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Donkey Betz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Header />
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
