"""Init Migration

Revision ID: 2e2cf97bf714
Revises: 
Create Date: 2024-02-07 10:16:53.050935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e2cf97bf714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_token_token'), ['token'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_category_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tag_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_username_email', ['username', 'email', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('goal', sa.String(length=500), nullable=True),
    sa.Column('backstory', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('idx_agent_name_user_role', ['name', 'user_id', 'role', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('chatbots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('collection_name', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.create_index('idx_name_user_topic_collection', ['name', 'user_id', 'collection_name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbots_collection_name'), ['collection_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbots_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_chatbots_user_id'), ['user_id'], unique=False)

    op.create_table('crews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('result_content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crews', schema=None) as batch_op:
        batch_op.create_index('idx_crew_name_user', ['name', 'user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crews_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crews_user_id'), ['user_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_title_user', ['title', 'user_id', 'date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_draft'), ['is_draft'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    op.create_table('user_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_query_user_id'), ['user_id'], unique=False)

    op.create_table('agent_chatbot_table',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'chatbot_id')
    )
    op.create_table('agent_crew_mapping',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'crew_id')
    )
    op.create_table('chatbot_interactions_table',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chatbot_id')
    )
    op.create_table('chatbot_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_types', sa.String(), nullable=True),
    sa.Column('content_sources', sa.String(), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('tool_preferences', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_preferences_chatbot_id'), ['chatbot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_preferences_content_sources'), ['content_sources'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_preferences_topic_types'), ['topic_types'], unique=False)

    op.create_table('chatbot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personality_type', sa.String(length=50), nullable=True),
    sa.Column('interaction_mode', sa.String(), nullable=True),
    sa.Column('voice_type', sa.String(length=10), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_settings', schema=None) as batch_op:
        batch_op.create_index('idx_personality_interaction_voice', ['personality_type', 'interaction_mode', 'voice_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_settings_chatbot_id'), ['chatbot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_settings_interaction_mode'), ['interaction_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_settings_personality_type'), ['personality_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_settings_voice_type'), ['voice_type'], unique=False)

    op.create_table('conversation_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('conversation_status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', 'ENDED', name='conversationstatus'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_session', schema=None) as batch_op:
        batch_op.create_index('idx_user_topic_status', ['user_id', 'topic_name', 'conversation_status', 'last_accessed'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_session_chatbot_id'), ['chatbot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_session_conversation_status'), ['conversation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_session_last_accessed'), ['last_accessed'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_session_topic_name'), ['topic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_session_user_id'), ['user_id'], unique=False)

    op.create_table('post_categories_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('post_tags_table',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('crew_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_description_status_agent_crew', ['description', 'status', 'agent_id', 'crew_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_crew_id'), ['crew_id'], unique=False)

    op.create_table('user_agent_table',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'agent_id')
    )
    op.create_table('agent_tasks_table',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'task_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_session_sender_type', ['session_id', 'sender_id', 'message_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('chatbot_tool_link',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_preferences_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_preferences_id'], ['chatbot_preferences.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'chatbot_preferences_id')
    )
    op.create_table('task_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('result_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_results', schema=None) as batch_op:
        batch_op.create_index('idx_task_result_task_id', ['task_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_results_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_results_task_id'))
        batch_op.drop_index('idx_task_result_task_id')

    op.drop_table('task_results')
    op.drop_table('chatbot_tool_link')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_id'))
        batch_op.drop_index('idx_session_sender_type')

    op.drop_table('chat_messages')
    op.drop_table('agent_tasks_table')
    op.drop_table('user_agent_table')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_crew_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_agent_id'))
        batch_op.drop_index('idx_task_description_status_agent_crew')

    op.drop_table('tasks')
    op.drop_table('post_tags_table')
    op.drop_table('post_categories_table')
    with op.batch_alter_table('conversation_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_session_topic_name'))
        batch_op.drop_index(batch_op.f('ix_conversation_session_last_accessed'))
        batch_op.drop_index(batch_op.f('ix_conversation_session_conversation_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_session_chatbot_id'))
        batch_op.drop_index('idx_user_topic_status')

    op.drop_table('conversation_session')
    with op.batch_alter_table('chatbot_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_settings_voice_type'))
        batch_op.drop_index(batch_op.f('ix_chatbot_settings_personality_type'))
        batch_op.drop_index(batch_op.f('ix_chatbot_settings_interaction_mode'))
        batch_op.drop_index(batch_op.f('ix_chatbot_settings_chatbot_id'))
        batch_op.drop_index('idx_personality_interaction_voice')

    op.drop_table('chatbot_settings')
    with op.batch_alter_table('chatbot_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_preferences_topic_types'))
        batch_op.drop_index(batch_op.f('ix_chatbot_preferences_content_sources'))
        batch_op.drop_index(batch_op.f('ix_chatbot_preferences_chatbot_id'))

    op.drop_table('chatbot_preferences')
    op.drop_table('chatbot_interactions_table')
    op.drop_table('agent_crew_mapping')
    op.drop_table('agent_chatbot_table')
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_query_user_id'))
        batch_op.drop_index('idx_user_id_created_at')

    op.drop_table('user_query')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_posts_is_draft'))
        batch_op.drop_index('idx_post_title_user')

    op.drop_table('posts')
    with op.batch_alter_table('crews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crews_user_id'))
        batch_op.drop_index(batch_op.f('ix_crews_name'))
        batch_op.drop_index('idx_crew_name_user')

    op.drop_table('crews')
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbots_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatbots_name'))
        batch_op.drop_index(batch_op.f('ix_chatbots_collection_name'))
        batch_op.drop_index('idx_name_user_topic_collection')

    op.drop_table('chatbots')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_agents_role'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index('idx_agent_name_user_role')

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_username_email')

    op.drop_table('users')
    op.drop_table('tools')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index('idx_tag_name')

    op.drop_table('tags')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index('idx_category_name')

    op.drop_table('categories')
    with op.batch_alter_table('blacklisted_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_token_token'))

    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
